### ISSUE TITLE
Document taal

### ISSUE THREAD

**Issue by SanHont** [Robin1224/the-client-website-2023#1]
Het is handig om je document als taal op het nederlands te zetten inplaats van engels als het een nederlandstalige website is.

https://github.com/Robin1224/the-client-website-2023/blob/773d2c4b506446a0fb864379c8911659cbb4768d/index.html#L3

**Comment by Robin1224** [comment]
De document taal was indd verkeerd ingesteld
Document taal is aangepast in de HTML

Thanks voor de feedback :)
